apputil.hpp: conditionally define STON for size_t
In some architectures like i386, `size_t` is same as `unsigned int`.
Then it causes redefinition error.

```
/<<PKGBUILDDIR>>/apps/apputil.hpp:101:24: error: redefinition of ‘Number StrToNumber(const string&) [with Number = unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]’
 template<> inline type StrToNumber(const std::string& s) { return function (s, 0, 0); }
                        ^~~~~~~~~~~
/<<PKGBUILDDIR>>/apps/apputil.hpp:107:1: note: in expansion of macro ‘STON’
 STON(unsigned int, stoul);
 ^~~~
/<<PKGBUILDDIR>>/apps/apputil.hpp:101:24: note: ‘Number StrToNumber(const string&) [with Number = unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]’ previously declared here
 template<> inline type StrToNumber(const std::string& s) { return function (s, 0, 0); }
                        ^~~~~~~~~~~
/<<PKGBUILDDIR>>/apps/apputil.hpp:105:1: note: in expansion of macro ‘STON’
 STON(size_t, stoul);
```